<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TermekSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //gyűrűk
        DB::table('termek')->insert([
            ['nev' => '14 KARÁTOS SÁRGA ARANY SIMA KARIKAGYŰRŰPÁR',
                'leiras' => 'Azoknak akik a letisztult stílust kedvelik, de mégis szeretnek kitűnni a tömegből.',
                'ar' => 150000, 'mennyiseg' => 15, 'kategoria_id' => 4],
            ['nev' => '14 KARÁTOS SÁRGA-FEHÉR ARANY KARIKAGYŰRŰPÁR',
                'leiras' => 'Sárga-fehér arany kombináció a tökéletes hatás eléréséhez.',
                'ar' => 180000, 'mennyiseg' => 10, 'kategoria_id' => 4],
            ['nev' => 'EZÜST PECSÉT GYŰRŰ CIRKÓNIA KŐVEL',
                'leiras' => 'Bármilyen eseményhez könnyedén illő ezüstgyűrű.',
                'ar' => 30000, 'mennyiseg' => 3, 'kategoria_id' => 5],
            ['nev' => 'EZÜST PECSÉT GYŰRŰ ONIX KŐVEL',
                'leiras' => 'Ezüst gyűrű a közepén fekete cirkónia kővel, de vajon mit rejt a sötétéség?',
                'ar' => 35000, 'mennyiseg' => 30, 'kategoria_id' => 5],
            ['nev' => 'FEKETE, FINOM MINTÁS FELSZÍNŰ ACÉLGYŰRŰ',
                'leiras' => 'Tartós rozsdamentes acélból készült gyűrű plasztikus mintázattal.',
                'ar' => 6000, 'mennyiseg' => 15, 'kategoria_id' => 6],
            ['nev' => 'SPANYOL IMASZÖVEGES, FEKETE SZÍNŰ ACÉLGYŰRŰ',
                'leiras' => 'Nikkel-tesztelt, Keresztény motívumos gyűrű.',
                'ar' => 6999, 'mennyiseg' => 5, 'kategoria_id' => 6],
            ['nev' => 'FEKETE-PIROS MINTÁS EZÜSTSZÍNŰ ACÉLGYŰRŰ',
                'leiras' => 'Tartós rozsdamentes acélból készült egyedülálló és izgalmas kialakítású gyűrű.',
                'ar' => 5200, 'mennyiseg' => 17, 'kategoria_id' => 6],
            ['nev' => 'Fehérarany Gyémánt Tanzanit Gyűrű',
                'leiras' => 'Tudtad, hogy a meseszép tanzanit a világ legritkább drágaköve? Épp ezért más kezén nem is ragyoghatna szebben, mint a tiéden.',
                'ar' => 1500000, 'mennyiseg' => 4, 'kategoria_id' => 7],
            ['nev' => 'Hollywood Moments Gyémánt Topáz Gyűrű',
                'leiras' => 'Egy remekmű az ujjadon, melynek viselésével valódi filmsztárnak érzed magad.',
                'ar' => 1800000, 'mennyiseg' => 7, 'kategoria_id' => 7],
            ['nev' => 'Az egy gyűrű',
                'leiras' => 'Egyet hordjon a Sötét Úr, szolganyájat terelő, Mordor éjfekete földjén, sűrű árnyak mezején.',
                'ar' => 100000000, 'mennyiseg' => 5, 'kategoria_id' => 8],
            ['nev' => 'Nathan Drake gyűrűje',
                'leiras' => 'Egykor Francis Drake kalóz gyűrűje volt, a rajta álló szöveg SIC PARVIS MAGNA jelentése: nagy kezd kicsiben.',
                'ar' => 80000000, 'mennyiseg' => 9, 'kategoria_id' => 8],
        ]);

        //órák
        DB::table('termek')->insert([
            ['nev' => 'Rolex Day-date',
                'leiras' => 'Oyster Perpetual Day-Date 18 karátos sárgaaranyból, gyémántokkal kirakott számlap, gyémántokkal kirakott lünetta és President karperec.',
                'ar' => 36350000, 'mennyiseg' => 3, 'kategoria_id' => 9],
            ['nev' => 'Rolex Datejust',
                'leiras' => 'Ez az Oyster Perpetual Datejust 36 Oystersteelből és fehéraranyból készült, rózsaszín, gyémántokkal kirakott számlappal és Oyster karpereccel.',
                'ar' => 6350000, 'mennyiseg' => 5, 'kategoria_id' => 9],
            ['nev' => 'Rolex Day-Date 40',
                'leiras' => 'Oyster Perpetual Day-Date 40 18 karátos fehéraranyból, élénk kék számlappal, gyémántokkal kirakott lünetta és President karperec.',
                'ar' => 7180000, 'mennyiseg' => 6, 'kategoria_id' => 9],
            ['nev' => 'Rolex Day-Date 36',
                'leiras' => 'Oyster Perpetual Day-Date 36 in 18 ct yellow gold, with a green ombré, diamond-set dial, diamond-set bezel and a diamond-set President bracelet.',
                'ar' => 10980000, 'mennyiseg' => 6, 'kategoria_id' => 9],
            ['nev' => 'Rolex Lady-datejust',
                'leiras' => 'Ez az Oyster Perpetual Lady-Datejust 18 karátos Everose aranyból készült, padlizsánszínű, gyémántokkal kirakott számlap és Jubilee karperec.',
                'ar' => 13550000, 'mennyiseg' => 4, 'kategoria_id' => 9],
            ['nev' => 'Rolex Cellini Moonphase',
                'leiras' => 'Cellini Moonphase 18 ct Everose aranyból, bőrszíjjal.',
                'ar' => 9515000, 'mennyiseg' => 3, 'kategoria_id' => 10],
            ['nev' => 'Rolex Day-Date 36 Arany',
                'leiras' => 'Oyster Perpetual Day-Date 36 18 karátos sárgaaranyból, pezsgőszínű számlap, bordázott lünetta és President karperec.',
                'ar' => 13550000, 'mennyiseg' => 8, 'kategoria_id' => 10],
            ['nev' => 'selfwinding flying tourbillon',
                'leiras' => 'Az új Selfwinding Flying Tourbillon füstszürke, napszürke "Tapisserie" számlapja, amely a repülő tourbillon ketrecből sugárzik.',
                'ar' => 42720000, 'mennyiseg' => 7, 'kategoria_id' => 10],
            ['nev' => 'royal oak selfwinding flying tourbillon',
                'leiras' => 'A Royal Oak Flying Tourbillon ketrecéből kialakuló zöld napfényes Tapisserie számlapja erősíti a 18 karátos rózsaszín arany tok és a karperec elegáns árnyalatait.',
                'ar' => 42720000, 'mennyiseg' => 10, 'kategoria_id' => 10],
            ['nev' => 'royal oak selfwinding Chronograph',
                'leiras' => 'Ez a Japánnak szentelt 41 mm-es Cronographegy 18 karátos sárgaaranyból készült, fagyott arannyal csillogó tokot és egy sárgaarany színű "Grande Tapisserie" számlapot ötvöz.',
                'ar' => 48320000, 'mennyiseg' => 5, 'kategoria_id' => 10],
            ['nev' => 'Patek Philippe Nautilus',
                'leiras' => 'Az éves naptárral és holdfázis kijelzéssel ellátott acél Nautilus új, kék számlapot kapott, amelyet az eredeti, 1976-os Nautilus modell számlapszíne ihletett.',
                'ar' => 78835000, 'mennyiseg' => 11, 'kategoria_id' => 11],
            ['nev' => 'Patek Philippe Complications',
                'leiras' => 'A referencia 5905 önfelhúzós flyback kronográf éves naptárral, amely most először kapható acélból, határozottan sportos megjelenést sugároz.',
                'ar' => 43000000, 'mennyiseg' => 15, 'kategoria_id' => 11],
            ['nev' => 'Patek Philippe Aquanat',
                'leiras' => 'Az Aquanaut 1997-es bevezetésekor szenzációt keltett. Fiatalos, modern és váratlan volt.',
                'ar' => 35750000, 'mennyiseg' => 9, 'kategoria_id' => 11],
            ['nev' => 'Patek Philippe Twenty4',
                'leiras' => 'Egy vadonatúj, önfelhúzós mechanikus női karórát dobott piacra, amelyet úgy terveztek, hogy stílusosan adja meg az élet ritmusát a modern, aktív nők számára.',
                'ar' => 55715000, 'mennyiseg' => 7, 'kategoria_id' => 11],
            ['nev' => 'Patek Philippe Aquanat',
                'leiras' => 'A Patek Philippe újraértelmezi a kvarc Aquanaut Luce-t rozsdamentes acélból, nagyobb átmérővel (38,8 mm) és új integrált kompozit szíjjal.',
                'ar' => 35750000, 'mennyiseg' => 10, 'kategoria_id' => 11],
            ['nev' => 'Patek Philippe Grand Compilations',
                'leiras' => 'Önfelhúzós mechanikus szerkezet. Kaliber 240 LU CL C. Kézi dátumozás.',
                'ar' => 45000000 , 'mennyiseg' => 3, 'kategoria_id' => 12],
            ['nev' => 'Patek Philippe Grand Compilations',
                'leiras' => 'A kronográf mindig is kiemelkedő szerepet játszott azon komplikációk széles skáláján, amelyekben a Patek Philippe bizonyította virtuozitását.',
                'ar' => 45000000, 'mennyiseg' => 5, 'kategoria_id' => 12],
            ['nev' => 'Patek Philippe Grand Compilations',
                'leiras' => 'Az első olyan percismétlő, amely mindig a helyi időt üti, innovatív módon egyesíti a Patek Philippe két legemblematikusabb komplikációját.',
                'ar' => 42000000, 'mennyiseg' => 8, 'kategoria_id' => 12],
            ['nev' => 'Patek Philippe Grand Compilations',
                'leiras' => 'A Patek Philippe legbonyolultabb karórája egyesíti a teljesítményt és az eleganciát egy új fehérarany változatban, amely elöl és hátul kék opálos számlappal büszkélkedhet.',
                'ar' => 45500000, 'mennyiseg' => 6, 'kategoria_id' => 12],
            ['nev' => 'Patek Philippe Grand Compilations',
                'leiras' => 'Ez az új nagy komplikáció kifejezetten a feltűnő órák kedvelői számára készült.',
                'ar' => 48000000, 'mennyiseg' => 4, 'kategoria_id' => 12],
        ]);

        //nyakláncok
        DB::table('termek')->insert([
            ['nev' => 'Millenia',
                'leiras' => 'Dinamikus tervezés találkozik az időtlen eleganciával ebben gyönyörű medálban.',
                'ar' => 34500, 'mennyiseg' => 20, 'kategoria_id' => 13],
            ['nev' => 'Birthstone medál',
                'leiras' => 'A Swarovski medált a születési hónapokra utaló kövek tradíciója, valamint a hónapokhoz kapcsolódó drágakövek ihlették.',
                'ar' => 26500, 'mennyiseg' => 23, 'kategoria_id' => 13],
            ['nev' => 'Dazzling Swan nyaklánc',
                'leiras' => 'Tárja fel a fekete-fehér divat új dimenzióit a Swarovski ikonikus hattyú szimbólummal díszített megfordítható nyakláncot viselve.',
                'ar' => 41500, 'mennyiseg' => 17, 'kategoria_id' => 13],
            ['nev' => 'glamira medal kalin',
                'leiras' => 'Sárga arany 585 / Barna gyémánt & Briliáns',
                'ar' => 3331635, 'mennyiseg' => 18, 'kategoria_id' => 14],
            ['nev' => 'glamira medál chofa',
                'leiras' => 'Fehér arany 585 / Gyémánt & Swarovski kristály',
                'ar' => 7211523, 'mennyiseg' => 30, 'kategoria_id' => 14],
            ['nev' => 'glamira medál acantha',
                'leiras' => 'Sárga arany 585 / Barna gyémánt & Gyémánt',
                'ar' => 556984, 'mennyiseg' => 5, 'kategoria_id' => 14],
            ['nev' => 'glamira medál alzira',
                'leiras' => 'Fehér arany 585 / Barna gyémánt & Gyémánt & Swarovski kristály',
                'ar' => 4293091, 'mennyiseg' => 9, 'kategoria_id' => 14],
            ['nev' => 'ragyogó kereszt medál',
                'leiras' => 'Sterling ezüst medál 2 db mikro, peremes foglalású és 23 db peremes foglalású áttetsző cirkóniával, szív alakú bemetszésekkel.',
                'ar' => 16500, 'mennyiseg' => 13, 'kategoria_id' => 14],
            ['nev' => 'Vastag anker nyaklánc',
                'leiras' => 'Válaszd a klasszikus stílust a Vastag anker nyaklánccal!',
                'ar' => 26500, 'mennyiseg' => 12, 'kategoria_id' => 15],
            ['nev' => 'Pandora ME édesvízben tenyésztett gyöngyös nyaklánc',
                'leiras' => 'Ez a Pandora ME édesvízben tenyésztett gyöngyös nyaklánc sterling ezüstből készült, és az ikonikus gyöngyös stílust párosítja a vagány eleganciával.',
                'ar' => 74900, 'mennyiseg' => 7, 'kategoria_id' => 15],
            ['nev' => 'Szív családfa collier nyaklánc',
                'leiras' => 'Tartsd a szívedhez közel szeretteidet a Szív családfa collier nyaklánccal!',
                'ar' => 20500, 'mennyiseg' => 17, 'kategoria_id' => 15],
            ['nev' => 'GLAMIRA Pendant Carica',
                'leiras' => '925 Ezüst / Barna gyémánt',
                'ar' => 50375, 'mennyiseg' => 21, 'kategoria_id' => 16],
            ['nev' => 'GLAMIRA Pendant Potence',
                'leiras' => '925 Ezüst / Barna gyémánt',
                'ar' => 64120, 'mennyiseg' => 14, 'kategoria_id' => 16],
            ['nev' => 'rose des vents medallion necklace',
                'leiras' => 'Victoire de Castellane újraértelmezi Monsieur Dior szerencsecsillagát egy szélrózsa - egy nyolcágú csillag - formájában.',
                'ar' => 1752000, 'mennyiseg' => 9, 'kategoria_id' => 17],
            ['nev' => 'rose des vents necklace',
                'leiras' => 'Victoire de Castellane újraértelmezi Monsieur Dior szerencsecsillagát egy nyolcágú csillaggal díszített szélrózsa formájában.',
                'ar' => 632000, 'mennyiseg' => 5, 'kategoria_id' => 17],
        ]);
    }
}
